import type { Metadata } from "next";
import { Patrick_Hand } from "next/font/google";
import "./globals.css";
import "remixicon/fonts/remixicon.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

const patrick = Patrick_Hand({
  subsets: ["latin"],
  variable: "--font-patrick",
  weight: ["400"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${patrick.variable} antialiased bg-custom-gradient font-patrick`}
        suppressHydrationWarning
      >
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
